[general]
launch_at_login = true
show_in_menu_bar = true

[hotkeys]
# Spotlight replacement
fuzzy = "cmd+space"


[[smartlinks]]
name = "Google"
keyword = "g"
url = "https://www.google.com/search?q={query}"
